import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";

import fs from "fs/promises";
import path from "path";

export default function Home({ products }) {
	return (
		<div className={styles.container}>
			<Head>
				<title>rsBlog</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Layout>
				<h1>Hello world, this is NEXT</h1>
				<Link href='/signup'>
					<a>Signup</a>
				</Link>
				<ul>
					{products.map(product => (
						<li key={product.id}>{product.title}</li>
					))}
				</ul>
			</Layout>

			<footer className={styles.footer}>
				<a
					href='https://rosario.solutions'
					target='_blank'
					rel='noopener noreferrer'
				>
					Built by{" "}
					<span className={styles.logo}>
						<Image src='/logo.jpg' alt='Rosario Logo' width={60} height={16} />.
						Powered by NEXTjs and Reactjs.
					</span>
				</a>
			</footer>
		</div>
	);
}
export const getStaticProps = async () => {
	const filePath = path.join(process.cwd(), "dummy-data.json");
	const jsonData = await fs.readFile(filePath);
	const data = JSON.parse(jsonData);

	return {
		props: {
			products: data.products
		},
		// in production
		revalidate: 10
	};
};
